- name: Default workspace configuration
  hosts: all
  vars:
    dotfiles_dir: ~/dotfiles
  environment:
    http_proxy: http://proxy.corpnet.inside:8080
    https_proxy: http://proxy.corpnet.inside:8080
  tasks:
    - name: Install Git
      package: name=git state=latest
      become: yes
    - name: Checkout '{{ dotfiles_dir }}'
      ansible.builtin.git:
        repo: 'https://github.com/rzabcio/dotfiles.git'
        dest: '{{ dotfiles_dir }}'
    - name: Install other tools
      package:
        name:
          - tmux
          - vifm
          - vim
          - zsh
        state: latest
      become: yes
      ignore_errors: yes
    - name: Distribution
      debug: msg='{{ ansible_distribution }}'
    - name: Install other tools - RedHat/CentOS
      package:
        name:
          - ctags
        state: latest
      become: yes
      ignore_errors: yes
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - name: Install other tools - other
      package:
        name:
          - exuberant-tags
          - fdfind
        state: latest
      become: yes
      ignore_errors: yes
      when: ansible_distribution != 'CentOS' and ansible_distribution != 'RedHat'

